### ISSUE TITLE
Where is database connection established?

### ISSUE THREAD

**Issue by guswelter** [neo4j/neo4j-go-driver#113]
Hello,

I am using v1.8.0 of the driver and v3.5 of the database (for testing purposes).

I establish a driver instance and session expecting that the former (or at least the latter) will actually connect to the database and yield an error upon not being able to do so, but testing with no database running yields no errors. Here is the code:

```
config := func(conf *neo4j.Config) {}
dbd, err = neo4j.NewDriver("bolt://localhost:7687", neo4j.BasicAuth("...", "...", ""), config)
if err != nil {
	panic(fmt.Sprintf("error connecting to neo4j: %s", err))
}
dbs, err = dbd.Session(neo4j.AccessModeRead)
if err != nil {
	panic(fmt.Sprintf("error initiating session with neo4j: %s", err))
}
```

I cannot find it explicitly stated in the documentation, though I can find conflicting and (to me) ambiguous statements for whether NewDriver is supposed to establish a connection:

From the readme: 
> Each Driver instance maintains a pool of connections inside

and

> sessions and transactions do not create new connections as long as there are free connections available in the connection pool.

From godoc:

> Session represents a logical connection (which is not tied to a physical connection) to the server

Note: I don't what a logical vs physical connection would be in this case. If the driver is not actually talking to the database at all, I wouldn't call it a connection of any sort, incl. a logical one.

So, my questions & suggestions are:
- Is Driver or Session supposed to connect to the database and yield an error on connection failure?
- If not, is there a way to establish a connection to the database other than executing a query?
- If not, I would suggest that there should be a mechanism to do this. It is desirable in many cases to fail early e.g. upon service startup if a database connection is not available.
- Lastly, I would suggest these matters be clarified in the documentation.

Thank you!

**Comment by 2hdddg** [comment]
Hi @guswelter 
Good suggestions and comments. I think some of the other drivers has a verify function on the driver instance. Since the 1.8 release is intended to be backwards compatible and not add anything (besides multidb functionality) I haven't added it. I'm pretty sure (but not 100%) that the 1.7 driver worked the same way (please say if it isn't).

I prefer new driver to not connect to the database, could be bad if running db and app in different containers/servers, the database server might not be up at the point where the app starts, the current way would just start working after a while.

Regarding the session, there is a problem in a clustered environment with different readers and writers, we don't know which one to connect until a statement is issued and always connect to something would be bad for performance.

Maybe we should not return errors from these function to clearify that not much could go wrong except bad params or even a panic (not very fond of that normally). And certainly the documentation should clearify this.

**Comment by 2hdddg** [comment]
I will add a VerifyConnection method on the driver object.

**Comment by guswelter** [comment]
That's perfect, thanks!
