### ISSUE TITLE
[Feature Request] Add Reset() to neo4j.Result

### ISSUE THREAD

**Issue by Aoi-hosizora** [neo4j/neo4j-go-driver#133]
### Versions

`Neo4j` 3.5.8
`github.com/neo4j/neo4j-go-driver` v1.8.1

### Problem

I want to get the `neo4j.Record` number first from `neo4j.Result` before handle it, so I have to use the `for result.Next() { }` twice.

The implement of `neo4j.Result`, which is `neo4j.result`, used `iter iterator` field to fetch data. But there is no `Reset` method in `neo4j.Result` interface (there is only `Next` to move to next and `Record` to get the current record) to allow me to reset the iterator. So please add this.

### Sample Code

```go
// in one function
result.Reset() // <<<
for result.Next() {
    // handle with result.Record()
}

// in another function
result.Reset() // <<<
for result.Next() {
    // handle with result.Record()
}
```

**Comment by 2hdddg** [comment]
Hi @Aoi-hosizora 
Result is strictly forward only, for reset to work records would need to be buffered. In some special cases the records are buffered, the iterator you see in the code is for those special cases. Since results can be potentially very big we really don't want to buffer!

In your case you should be able to retrieve the value from the result first and then send that to both functions that uses the result as a parameter instead, or you can buffer all records from the result yourself first and send the slice of records to your functions (beware that this could consume a lot of memory when there are a lot of rows).

**Comment by Aoi-hosizora** [comment]
Thanks! Maybe I should not do in this way. I will find another way to get the Record count better.
