### ISSUE TITLE
[Feature Request] Updating existing errors to work with the Go 1.13+ error

### ISSUE THREAD

**Issue by marvinkite** [neo4j/neo4j-go-driver#161]
After Go 1.13, the standard way to handle wrapped errors is with the standard library: https://blog.golang.org/go1.13-errors
Implementing Unwrap will allow to check the original error with errors.Is and errors.As.

I try to switch from 1.8 driver because of ~20% fail rate with with Aura even after the last fix in 1.8.3 and now I try to migrate to the new driver and I'm trying to implement the error handling. I noticed for some error it's more comfortable to not to use the `neo4j.Isxxx` methods but the 1.13 API may improve the usability bit more.

**Comment by 2hdddg** [comment]
Thanks for trying out 4.0!

You don't have to use the neo4j.Isxxx functions on 4.0, the error types are exported so you can check with as/is. Regarding unwrap would only make sense on ConnectivityError as that is the only exported error with a single inner error and you would only be able to determine if it is io.EOF or not.

Maybe better if you specify the failures you see with Aura so that we can fix that instead, it is easier to fix within the driver than outside. 

You should only use session.ReadTransaction/WriteTransaction when working with Aura, session.Run and Session.BeginTransaction are not covered by the retry logic.

**Comment by 2hdddg** [comment]
Hi @marvinkite 
I can see from your previous issue on "Driver fail to reconnect" that you are using session.Run. We probably need to be a lot clearer in documentation about when it is safe to use session.Run, against a cluster it is not. 

You must rewrite your code to use ReadTransaction/WriteTransaction. To use the returned error to reimplement the retry logic is not recommended.

**Comment by marvinkite** [comment]
Hi Peter,

Thanks for the advises. Yes indeed some more accurate documentation could help. Until yesterday I was using 1.8.3 with `session.Run()` everywhere and indeed I see high number of failure with Aura. List night I migrated the driver to latest 4.0 and I learned the new API and I rewrote to use the ReadTransaction/WriteTransaction instead. Let me share with you my experience and please correct me if I don't use the driver appropriately so the documentation can be updated bases on my mistakes. 

We are building a platform on top of Neo4j for millions of users so stability and performance will be critical for us. We desperately looking for Noe4j experts in Scandinavia or in that timezone but it's hard to find. We have a growing service mesh and many of our services depends on Neo4j so I'm trying to make a library which makes easy to use the graph. 

When the application starts I create a `neo4j.NewDriver` and when the application exits I Close it. Extreme case when I use in a serverless environment. Either I do the full New-Close lifecycle in scope of handling a single request which seems an overkill or I lazy initialise the `Driver` and due to the nature of Google CloudFunction or CloudRun I have no way to close the driver and release the resources. I hope it does not leave too much open connection at server side. 

Once I have the `Driver` instance I share the same instance among concurrent calls. In each function when I handle concurrently request each time I create a new session.  

```golang
	if readOnly {
		session := driver.NewSession(neo4j.SessionConfig{AccessMode: neo4j.AccessModeRead})
		resp, err = session.ReadTransaction(func(tx neo4j.Transaction) (interface{}, error) {
			return op(parent, tx.Run)
		}, opts...)
		_ = session.Close()
	} else {
		session := driver.NewSession(neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite})
		resp, err = session.WriteTransaction(func(tx neo4j.Transaction) (interface{}, error) {
			return op(parent, tx.Run)
		}, opts...)
		_ = session.Close()
	}
```

Here the `AccessMode` has no relevance because I'm not using `Run` or `BeginTransaction`. The `ReadTransaction/WriteTransaction` returns with a `retryableTransaction` which only have one the `Run` method that can be used. (The Commit/Rollback/Close returns UsageError).

At the end I have an http handler function that willing to execute some Cypher. I made a utility  that creates a new session, configures it and hands over to my operation `CypherOp` a single function to execute one or more cyphers in the same transaction.

```golang 
type (
	TxRun    func(cypher string, params map[string]interface{}) (neo4j.Result, error)
	CypherOp func(context.Context, TxRun) (interface{}, error)
)
```

For performance I'd like to also measure the execution time so I have [OpenTelemetry](https://opentelemetry.io/) trace around it. 

I don't know yet how the best use the metadata and what for. For now I just put the trace span id and I will investigate it further.

```golang
  opts = []func(*neo4j.TransactionConfig){neo4j.WithTxMetadata(map[string]interface{}{
    "span_id": span.SpanContext().SpanID.String()})}
```

Back to the Error handling, I try to establish a convention among our developer how to handle response and errors like when response may or may not have a single record.

```golang
	result, err := rx.Run(cypherQuery, params)
	if err != nil {
		return nil, err
	}
	record, err := result.Single()
	if neo4j.IsUsageError(err) {
		if "Result contains no more records" == err.Error() {
			err = errEmptyResponse
		} else if "Result contains more than one record" == err.Error() {
			err = errMultipleResponse
		}
	}
	if err != nil {
		return nil, err
	}
```
I used to have my own `Single` implementation and I think I will go back because I don't like to check the error based on the message.

We still need to learn more about how the server responses and adjust this code more but I still share it. It's a last night quick draft so I will change. Maybe try to use more the 1.13+ functions here but I will keep you updated. We try to match to gRPC error and probably logging now to learn more but so far we just use this function to understand the error.

```golang
func StatusError(err error) *status.Status {
	if err == nil {
		return nil
	}
	if v, ok := err.(interface {
		GRPCStatus() *status.Status
	}); ok {
		return v.GRPCStatus()
	}

	switch e := err.(type) {
	case *neo4j.Neo4jError:
		if e.IsAuthenticationFailed() {
			return status.New(codes.Internal, err.Error())
		} else if e.IsRetriableCluster() || e.IsRetriableTransient() {
			return status.New(codes.Unavailable, err.Error())
		}
		switch e.Code {
		case "Neo.ClientError.Schema.ConstraintValidationFailed":
			return status.New(codes.AlreadyExists, err.Error())
		case "Neo.ClientError.Statement.ParameterMissing", "Neo.ClientError.Procedure.ProcedureCallFailed":
			return status.New(codes.Internal, err.Error())
		default:
			return status.New(codes.InvalidArgument, err.Error())
		}
	case *neo4j.UsageError:
	case *neo4j.ConnectivityError:
	case *neo4j.TransactionExecutionLimit:
	}
	if err == errEmptyResponse {
		return status.New(codes.NotFound, err.Error())
	}
	return status.New(codes.Unknown, err.Error())
}
```

I'm also using Zap structured logger and I will experiment bit more with it.

```golang
type logger struct {
	log  *zap.SugaredLogger
	core *zap.Logger
}

func (l *logger) Error(name string, id string, err error) {
	l.core.Error("Error", zap.String("name", name), zap.String("id", id), zap.Error(err))
}
func (l *logger) Errorf(name string, id string, msg string, args ...interface{}) {
	if l.core.Core().Enabled(zap.ErrorLevel) {
		l.core.Error(fmt.Sprintf(msg, args...), zap.String("name", name), zap.String("id", id))
	}
}
func (l *logger) Warnf(name string, id string, msg string, args ...interface{}) {
	if l.core.Core().Enabled(zap.WarnLevel) {
		l.core.Warn(fmt.Sprintf(msg, args...), zap.String("name", name), zap.String("id", id))
	}
}
func (l *logger) Infof(name string, id string, msg string, args ...interface{}) {
	if l.core.Core().Enabled(zap.InfoLevel) {
		l.core.Info(fmt.Sprintf(msg, args...), zap.String("name", name), zap.String("id", id))
	}
}
func (l *logger) Debugf(name string, id string, msg string, args ...interface{}) {
	if l.core.Core().Enabled(zap.DebugLevel) {
		l.core.Debug(fmt.Sprintf(msg, args...), zap.String("name", name), zap.String("id", id))
	}
}
```

I will keep you updated how it goes. Our next release is planned in a month and after that I can share more feedback.

**Comment by 2hdddg** [comment]
On overall it looks like it should work now that you are using transaction functions.

For the serverless environment, I guess you mean that you "lazy" initialize driver in init func as in PubSub example here?
https://cloud.google.com/functions/docs/bestpractices/networking
Connections to the database will be closed when the instances are removed.

I like your usage of the transaction interface where you only expose the Run function. That is the way the API should look but that would make the Go driver different API wise than the other drivers, I think that the API for transactional functions might change in the future to only have a Run function.

For the error handling... The UsageError means something that should be fixed while developing, you shouldn't see these in production if you test properly. I would even consider panic for these kind of errors or just map to internal error since you should really hit all of these before reaching production.

That also applies to the intended usage of Single, it is assumed to be used on Cypher
statements that is defined to return only a single record, otherwise the Cypher is wrong.
If you can get zero or more than one record back you shouldn't use Single. Consider 
using Collect instead (but be careful on potentially large results, since it will be
buffered) and check the size of the slice to return your own custom errors instead.

I would also consider some of the Neo4jError errors programming errors like ParameterMissing, ConstraintValidationFailed, ProcedureCallFailed.

As long as you use transactional functions you shouldn't see or at least there is nothing
for you to do on IsRetriableCluster or IsRetriableTransient errors, you should
get TransactionExecutionLimit error instead and that is clearly a codes.Unavailable.

I have never used Zap, looks nice! I guess that the driver could use a map instead 
of a formatting string with variadic fields to make it more structured but I'm not sure
how useful it would be in practice.

We appreciate the feedback and it is really nice that you started using 4.0! We hope to get a beta out really soon.
