### ISSUE TITLE
Query Not Returning Expected Results and Returning Zeros

### ISSUE THREAD

**Issue by bonesyo** [neo4j/neo4j-go-driver#183]
**Neo4j Version:** 4.2.1  
**Neo4j Mode**: Using Aura on GCP
**Driver version**: Go driver 4.2.1  
**Operating System:** Using Aura on GCP

### Steps to reproduce
I apologize since we can not reproduce this outside of our production DB, which contains sensitive data. We are running a larger query where about half way through the return data, it starts to return all Zeros for the return fields. EDIT: We have found that one of the results is chunked, and that is the result that it is getting corrupted.
### Expected behavior
The query should return valid data. When connecting to our DB from the Node driver, and running the same query we get expected results.
### Actual behavior
The query returns valid data to a certain point, then begins to return all zeros. We are not seeing anything in the logs.

**Comment by voutilad** [comment]
I can reproduce this issue with the following cypher running against Neo4j 4.2.2:

```
UNWIND [18432, 34143] AS n
  RETURN n, [_ IN range(1, n) | 'w'] AS text, "hello!" as msg
```

If you run the above, the 2nd record will have garbage null bytes in the middle of the very long array in the "text" field. The "msg" field will also be overwritten with a single "w" value instead of the expected string literal of `hello!`.
