### ISSUE TITLE
Error "imported and not used" while using go-driver

### ISSUE THREAD

**Issue by nadgowdas** [neo4j/neo4j-go-driver#48]
### System 

- Neo4j version: Community 3.5.2
- Driver version: go language driver 
- Operating system: MacOS/Ubuntu1804 
- **Steps to reproduce**
Using standard example from https://neo4j.com/developer/go/ 
While compiling, I am getting following error 
```
# github.ibm.com/demo-neo4j/vendor/github.com/neo4j/neo4j-go-driver
vendor/github.com/neo4j/neo4j-go-driver/direct.go:26:2: imported and not used: "github.ibm.com/demo-neo4j/vendor/github.com/neo4j-drivers/neo4j-go-connector" as gobolt
vendor/github.com/neo4j/neo4j-go-driver/direct.go:33:12: undefined: seabolt
vendor/github.com/neo4j/neo4j-go-driver/driver.go:26:2: imported and not used: "github.ibm.com/demo-neo4j/vendor/github.com/neo4j-drivers/neo4j-go-connector" as gobolt
vendor/github.com/neo4j/neo4j-go-driver/error.go:23:2: imported and not used: "github.ibm.com/demo-neo4j/vendor/github.com/neo4j-drivers/neo4j-go-connector" as gobolt
vendor/github.com/neo4j/neo4j-go-driver/result.go:23:2: imported and not used: "github.ibm.com/demo-neo4j/vendor/github.com/neo4j-drivers/neo4j-go-connector" as gobolt
vendor/github.com/neo4j/neo4j-go-driver/runner.go:24:2: imported and not used: "github.ibm.com/demo-neo4j/vendor/github.com/neo4j-drivers/neo4j-go-connector" as gobolt
vendor/github.com/neo4j/neo4j-go-driver/values_graph_handlers.go:26:2: imported and not used: "github.ibm.com/demo-neo4j/vendor/github.com/neo4j-drivers/neo4j-go-connector" as gobolt
vendor/github.com/neo4j/neo4j-go-driver/values_spatial_handlers.go:27:2: imported and not used: "github.ibm.com/demo-neo4j/vendor/github.com/neo4j-drivers/neo4j-go-connector" as gobolt
vendor/github.com/neo4j/neo4j-go-driver/values_temporal_handlers.go:27:2: imported and not used: "github.ibm.com/demo-neo4j/vendor/github.com/neo4j-drivers/neo4j-go-connector" as gobolt
```

The same problem is observed on Mac as well as Ubuntu1804. So it seems to be with the go-driver itself

**Comment by ali-ince** [comment]
Hi @nadgowdas,

I believe that you're trying to use a very early pre-release version of neo4j-go-driver, which is possibly because you've checked-in your vendor'ed dependencies into your internal repository. We had a couple of repository/package changes which may cause failures with the sample, created for the release version, to compile.

I suggest you to update/refresh dependencies using the following commands;

`dep ensure -update github.com/neo4j/neo4j-go-driver/neo4j`
`dep ensure -update github.com/neo4j-drivers/gobolt`

and update your source code with any API changes introduced in pre-release versions, please have a look at https://github.com/neo4j/neo4j-go-driver/wiki/1.7-changelog for a full list of changes.

The same applies to seabolt as well, you need to have the latest seabolt installed on your system.

Please have a look at https://github.com/neo4j/neo4j-go-driver for additional instructions.
