### ISSUE TITLE
Unable to set Thread pool

### ISSUE THREAD

**Issue by Inthecrowd** [neo4j/neo4j-go-driver#524]
The struct <driverWithContext> has pool property already, but there is no config available in func <NewDriverWithContext>'s params

**Comment by StephenCathcart** [comment]
Hi @Inthecrowd, would you be able to provide some more information on the open issue? 

For example -

* What driver version are you using?
* What is the expected behavior (i.e. what part of the driver are you using and how would you expect it to behave)?
* Do you have any sample code to show what you're running / would expect?

Thank you

**Comment by robsdedude** [comment]
I'm closing this now as we're lacking information. It's not really clear what the issue/feature request is here.

Please feel free to keep commenting with further input though. We can always re-open the issue if we decided there's need for action here.
