### ISSUE TITLE
Session.Run() does not delete nodes.

### ISSUE THREAD

**Issue by supercmmetry** [neo4j/neo4j-go-driver#77]
I am using Session.Run to run the following query:

`MATCH (n: Person) WHERE n.age > 17 DETACH DELETE n`

But no nodes are deleted.
However if I run the same query in the neo4j browser it works. In addition, CREATE and MATCH operations work in the session but deletion doesn't work.

The deletion happens when I close the Session though.
Here's the code:

```go
package main

import (
	"github.com/neo4j/neo4j-go-driver/neo4j"
)

func main() {
	driver, err := neo4j.NewDriver("bolt://localhost:7687", neo4j.BasicAuth("neo4j", "password", ""))

	if err != nil {
		panic(err)
	}

	session, err := driver.Session(neo4j.AccessModeWrite)

	if err != nil {
		panic(err)
	}

	_, err = session.Run("MATCH (n: Person) WHERE n.age > 17 DETACH DELETE n", map[string]interface{}{})

	if err != nil {
		panic(err)
	}
	
	// The nodes are not deleted yet.
	
	_ = session.Close()
	
	// The nodes are deleted after the session is closed.
}
```

**Comment by michael-simons** [comment]
You are running your query in an implicit transaction.

Would you mind not checking for `err`,  but using the returned `result` https://github.com/neo4j/neo4j-go-driver/blob/1.7/neo4j/result.go#L36 to consume it and retrieve the summary? That should commit the implicit transaction before closing the session.

Otherwise you can pass in a function that receives an ongoing transaction in which you should execute your statement:

https://github.com/neo4j/neo4j-go-driver/blob/1.7/neo4j/session.go#L35

The transaction will be committed and closed when the function returns.

Please let us know if that helps.

**Comment by supercmmetry** [comment]
It works now, thanks !
